---

- name: Debian | Ensure apt-transport-https is present
  package:
    name: apt-transport-https
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Debian | Set opensuse repo url
  set_fact:
    opensuse_url: "https://download.opensuse.org/repositories/security:/zeek/Debian_{{ ansible_distribution_version }}"
  when: ansible_distribution == 'Debian'

- name: Ubuntu | Set opensuse repo url
  set_fact:
    opensuse_url: "https://download.opensuse.org/repositories/security:/zeek/xUbuntu_{{ ansible_distribution_version }}"
  when: ansible_distribution == 'Ubuntu'

- block:
    - name: Debian | Add zeek repository key
      apt_key:
        url: >
          {{ opensuse_url }}/Release.key
        state: present
      register: pkg_result
      until: pkg_result is success
    - name: Debian | Add zeek repository
      apt_repository:
        repo: >
          deb {{ opensuse_url }}/ /
        state: present
    - name: Use Zeek opensuse variable
      include_vars: opensuse.yml
    
    - name: Include version-specific variables for Debian Buster.
      include_vars: "Debian-10.yml"
      when: ansible_distribution == 'Debian' and ansible_distribution_version == "10"
  
  when: not use_securityonion_deb

## WARNING: The following packages cannot be authenticated! = force
- debug: var=broids_packages
- debug: var=broids_packages_deps
- name: Debian/Ubuntu | Install Zeek and dependencies
  apt: name={{ broids_packages + broids_packages_deps }} state=present update_cache=yes cache_valid_time=3600
  register: pkg_result
  until: pkg_result is success

- name: update zeekctl LogDir
  replace:
    dest: "{{ broids_etc }}/zeekctl.cfg"
    regexp: "{{ item.re }}"
    replace: "{{ item.rep }}"
    backup: yes
  with_items:
    - { re: '^LogDir = .*', rep: "LogDir = {{ broids_log }}" }

- name: enable zeekctl MailConnectionSummary
  replace:
    dest: "{{ broids_etc }}/zeekctl.cfg"
    regexp: "^MailConnectionSummary = .*"
    replace: "MailConnectionSummary = 1"
    backup: yes
  when: bro_email_notification
- name: disable zeekctl MailConnectionSummary
  replace:
    dest: "{{ broids_etc }}/zeekctl.cfg"
    regexp: "^MailConnectionSummary = .*"
    replace: "MailConnectionSummary = 0"
    backup: yes
  when: not bro_email_notification

- name: ensure aide hids directory exists
  file: dest=/etc/aide/aide.conf.d state=directory mode=0755
- name: Add custom configuration for aide HIDS
  copy: "src={{ item }} dest=/etc/aide/aide.conf.d owner=root mode=0644"
  with_items:
    - aide-criticalstack

## from https://github.com/geerlingguy/drupal-vm/pull/456/files#diff-b1546b21a9366075f1e1245d7551eee6R11
- name: Detect if AppArmor is installed.
  stat:
    path: /etc/init.d/apparmor
  register: apparmor_installed
  when: travisci is defined and travisci

- name: Ensure MySQL AppArmor profile is disabled (for slow query log).
  file:
    path: /etc/apparmor.d/disable/usr.sbin.mysqld
    src: /etc/apparmor.d/usr.sbin.mysqld
    state: link
  when: travisci is defined and travisci and apparmor_installed.stat.exists
  notify:
    - Restart apparmor
